"""Static, reproducible charts (matplotlib) written to outputs/charts/.

Every chart is regenerated by scripts/build_outputs.py from the tables in
outputs/tables/ and data/processed/ — nothing is drawn by hand. Each PNG has
a table twin (the CSV it was drawn from), which is the accessible view.

Design rules (see the project's dataviz notes): one axis per chart (no dual
axes); categorical hues assigned in a fixed order, never cycled, validated
for colour-vision deficiency; a single series uses one colour; magnitude uses
a single-hue ramp; polarity (verification outcomes) uses a blue↔red
diverging scale with a neutral grey midpoint; hairline solid grids; text in
ink colours, never in series colours; no pie charts.
"""

from __future__ import annotations

import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from matplotlib.colors import LinearSegmentedColormap  # noqa: E402

# --- Palette (validated: scripts/validate_palette.js, light mode) -----------------
SURFACE = "#fcfcfb"
INK = "#0b0b0b"
INK_2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
AXIS = "#c3c2b7"
CATEGORICAL = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
SERIES_1 = CATEGORICAL[0]
DEEMPH = "#d9d8d2"
SEQ_BLUE = ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#184f95", "#0d366b"]
BLUE_CMAP = LinearSegmentedColormap.from_list("seq_blue", ["#f4f8fd"] + SEQ_BLUE)

# Verification outcomes: polarity -> diverging blue (supported) … grey … red (contradicted);
# the two non-factual outcomes and "unassessed" are neutral greys.
STATUS_ORDER = ["supported", "mostly_supported", "mixed_or_disputed", "misleading_without_context",
                "unsupported", "contradicted", "not_independently_verifiable", "opinion_or_interpretation"]
STATUS_COLORS = {
    "supported": "#184f95", "mostly_supported": "#6da7ec", "mixed_or_disputed": "#c3c2b7",
    "misleading_without_context": "#f0a3a2", "unsupported": "#e66767", "contradicted": "#b3302f",
    "not_independently_verifiable": "#898781", "opinion_or_interpretation": "#52514e",
}
STATUS_LABELS_ES = {
    "supported": "Respaldada", "mostly_supported": "Mayormente respaldada", "mixed_or_disputed": "Mixta / disputada",
    "misleading_without_context": "Engañosa sin contexto", "unsupported": "Sin respaldo", "contradicted": "Contradicha",
    "not_independently_verifiable": "No verificable independientemente", "opinion_or_interpretation": "Opinión / interpretación",
}

CHAPTER_SHORT = {
    "0. Preliminares": "0 Preliminares",
    "I. Proceso metodológico del empalme": "I Metodología",
    "II. Comportamientos críticos nocivos para el Estado": "II Comportamientos",
    "III. Hallazgos en materia de corrupción y balance de acciones": "III Corrupción",
    "IV. Balance sectorial": "IV Balance sectorial",
    "V. Principios de Gobierno de la Patria Milagro": "V Principios",
}
CHAPTER_ORDER = list(CHAPTER_SHORT)
SOURCE_NOTE = "Fuente: El Libro de la Verdad (2026); cálculos propios — petro-report-nlp-audit"

CHART_REGISTRY = [
    "01_document_overview", "02_words_per_section", "03_top_terms", "04_tfidf_terms", "05_top_bigrams",
    "06_top_trigrams", "07_entity_frequencies", "08_entity_cooccurrence_network", "09_topic_distribution",
    "10_topics_by_section", "11_semantic_embedding_map", "12_claim_categories", "13_claims_by_section",
    "14_verification_status_distribution", "15_verification_status_by_claim_type", "16_sources_cited_by_report",
    "17_sources_used_by_audit", "18_timeline_of_claims", "19_numeric_claims_dashboard",
    "20_causal_language_analysis", "21_framing_by_chapter", "22_stylometry_heatmap",
    "23_stylometry_similarity_matrix", "24_stylometry_change_points", "25_stylometry_pca_map",
    "26_sentiment_exploratory",
]


def setup_style() -> None:
    plt.rcParams.update({
        "figure.facecolor": SURFACE, "axes.facecolor": SURFACE, "savefig.facecolor": SURFACE,
        "font.family": "DejaVu Sans", "font.size": 9.5, "text.color": INK, "axes.labelcolor": INK_2,
        "axes.edgecolor": AXIS, "axes.linewidth": 0.8, "xtick.color": MUTED, "ytick.color": INK_2,
        "xtick.labelsize": 8.5, "ytick.labelsize": 8.5, "axes.grid": False, "grid.color": GRID,
        "grid.linewidth": 0.8, "grid.linestyle": "-", "axes.spines.top": False, "axes.spines.right": False,
        "axes.titlesize": 12, "axes.titleweight": "bold", "axes.titlelocation": "left", "axes.titlepad": 12,
        "legend.frameon": False, "legend.fontsize": 8.5,
    })


def _finish(fig, ax_or_none, out_path: Path, subtitle: str = "", note: str = SOURCE_NOTE) -> None:
    # Notes sit below the figure area; bbox_inches="tight" expands the canvas to include them,
    # so they never collide with axis labels.
    y = -0.02
    if subtitle:
        fig.text(0.01, y, subtitle, fontsize=7.5, color=INK_2, ha="left", va="top", wrap=True)
        y -= 0.045
    fig.text(0.01, y, note, fontsize=7, color=MUTED, ha="left", va="top")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150, bbox_inches="tight", pad_inches=0.25)
    plt.close(fig)


def _hbar(ax, labels, values, color=SERIES_1, fmt="{:,.0f}", max_label=None):
    y = np.arange(len(labels))[::-1]
    ax.barh(y, values, height=0.62, color=color, edgecolor=SURFACE, linewidth=1)
    ax.set_yticks(y, labels)
    ax.xaxis.grid(True)
    ax.set_axisbelow(True)
    ax.spines["left"].set_visible(False)
    ax.tick_params(axis="y", length=0)
    vmax = max(values) if len(values) else 1
    for yi, v in zip(y, values):
        ax.text(v + vmax * 0.01, yi, fmt.format(v), va="center", fontsize=7.5, color=INK_2)
    ax.set_xlim(0, vmax * 1.12)


def _short(s: str, n: int = 48) -> str:
    return s if len(s) <= n else s[: n - 1] + "…"


# --- 1-2 Structure ------------------------------------------------------------------------

def plot_document_overview(paragraphs: pd.DataFrame, n_pages: int, out: Path) -> None:
    """Page-by-page structure map: each page coloured by chapter, bar height = words on page."""
    p = paragraphs[paragraphs.block_type != "heading"]
    words = p.groupby("page").n_words.sum().reindex(range(1, n_pages + 1), fill_value=0)
    chap = p.groupby("page").chapter.first().reindex(range(1, n_pages + 1)).ffill().bfill()
    fig, ax = plt.subplots(figsize=(11, 3.4))
    for i, ch in enumerate(CHAPTER_ORDER):
        idx = chap[chap == ch].index
        ax.bar(idx, words.loc[idx], width=0.86, color=CATEGORICAL[i], label=CHAPTER_SHORT[ch])
    ax.yaxis.grid(True)
    ax.set_axisbelow(True)
    ax.set_xlim(0.3, n_pages + 0.7)
    ax.set_xlabel("Página del PDF")
    ax.set_ylabel("Palabras analizadas")
    ax.set_title("Mapa estructural del documento: palabras por página y capítulo")
    ax.legend(ncol=6, loc="upper left", bbox_to_anchor=(0, 1.02), handlelength=1, columnspacing=1.2)
    ax.set_ylim(0, words.max() * 1.25)
    _finish(fig, ax, out, "Páginas sin barra: cubierta, portadillas o páginas solo con imagen (texto por OCR excluido del análisis).")


def plot_words_per_section(words_df: pd.DataFrame, out: Path, top_n: int = 30) -> None:
    d = words_df[~words_df.level2.str.startswith("Portadilla")].sort_values("words", ascending=False).head(top_n)
    fig, ax = plt.subplots(figsize=(9, 0.26 * len(d) + 1.2))
    _hbar(ax, [_short(f"{CHAPTER_SHORT.get(c, c).split()[0]} · {s}", 60) for c, s in zip(d.chapter, d.level2)],
          d.words.values)
    ax.set_title(f"Palabras por sección (top {top_n})")
    ax.set_xlabel("Palabras")
    _finish(fig, ax, out)


# --- 3-6 Vocabulary ---------------------------------------------------------------------------

def plot_top_terms(freq: pd.DataFrame, out: Path, top_n: int = 25) -> None:
    d = freq.head(top_n)
    fig, ax = plt.subplots(figsize=(7.5, 0.24 * top_n + 1.2))
    _hbar(ax, d.term.tolist(), d["count"].values)
    ax.set_title("Términos más frecuentes (lemas, sin palabras vacías)")
    ax.set_xlabel("Frecuencia absoluta")
    _finish(fig, ax, out, "Números, fechas y signos excluidos del texto lematizado; 'millón'/'billón' provienen de cifras monetarias.")


def plot_tfidf_terms(chapter_tfidf: pd.DataFrame, out: Path, top_n: int = 8) -> None:
    chapters = [c for c in CHAPTER_ORDER if c in set(chapter_tfidf.chapter)]
    fig, axes = plt.subplots(2, 3, figsize=(12, 6.2))
    for ax, ch in zip(axes.ravel(), chapters):
        d = chapter_tfidf[chapter_tfidf.chapter == ch].sort_values("tfidf", ascending=False).head(top_n)
        _hbar(ax, d.term.tolist(), d.tfidf.values, fmt="{:.2f}")
        ax.set_title(CHAPTER_SHORT[ch], fontsize=10)
        ax.tick_params(axis="x", labelsize=7)
    for ax in axes.ravel()[len(chapters):]:
        ax.axis("off")
    fig.suptitle("Términos distintivos por capítulo (TF-IDF, capítulo = documento)", x=0.01, ha="left",
                 fontweight="bold", fontsize=12)
    fig.tight_layout(rect=(0, 0.02, 1, 0.96))
    _finish(fig, None, out, "TF-IDF sublineal sobre lemas; mide qué distingue a un capítulo de los demás, no su importancia.")


def plot_ngrams(ngrams: pd.DataFrame, out: Path, n: int = 2, top_n: int = 20) -> None:
    d = ngrams.head(top_n)
    fig, ax = plt.subplots(figsize=(7.5, 0.26 * top_n + 1.2))
    _hbar(ax, d.ngram.tolist(), d["count"].values)
    ax.set_title(("Bigramas" if n == 2 else "Trigramas") + " más frecuentes (lemas)")
    ax.set_xlabel("Frecuencia")
    _finish(fig, ax, out, "Calculados dentro de cada oración sobre texto lematizado sin palabras vacías.")


# --- 7-8 Entities -------------------------------------------------------------------------------

ENTITY_TYPES_SHOWN = ["ORG", "PERSON", "GPE_LOC", "LAW"]
ENTITY_TYPE_ES = {"ORG": "Organización", "PERSON": "Persona", "GPE_LOC": "Lugar", "LAW": "Norma / sentencia"}


def plot_entity_frequencies(entities: pd.DataFrame, out: Path, top_n: int = 25) -> None:
    d = entities[entities.entity_type.isin(ENTITY_TYPES_SHOWN)].head(top_n)
    colors = [CATEGORICAL[ENTITY_TYPES_SHOWN.index(t)] for t in d.entity_type]
    fig, ax = plt.subplots(figsize=(8.5, 0.26 * len(d) + 1.4))
    _hbar(ax, [_short(e, 55) for e in d.entity], d["count"].values, color=colors)
    handles = [plt.Rectangle((0, 0), 1, 1, color=CATEGORICAL[i]) for i in range(len(ENTITY_TYPES_SHOWN))]
    ax.legend(handles, [ENTITY_TYPE_ES[t] for t in ENTITY_TYPES_SHOWN], loc="lower right")
    ax.set_title("Entidades más mencionadas (NER spaCy + reglas)")
    ax.set_xlabel("Menciones")
    _finish(fig, ax, out, "Excluye fechas, cifras, términos genéricos ('Estado', 'Gobierno') y MISC. Alias fusionados solo si el propio documento define la sigla.")


def plot_network(graph_json: dict, out: Path, title: str, top_n: int = 40, label_n: int = 10,
                 color_by: str | None = "entity_type") -> None:
    import networkx as nx

    G = nx.Graph()
    for n in graph_json["nodes"]:
        G.add_node(n["id"], **n)
    for l in graph_json["links"]:
        G.add_edge(l["source"], l["target"], weight=l["weight"])
    if G.number_of_nodes():
        G = G.subgraph(max(nx.connected_components(G), key=len)).copy()  # largest connected component
    keep = sorted(G.nodes, key=lambda n: -G.nodes[n].get("weighted_degree", 0))[:top_n]
    H = G.subgraph(keep).copy()
    pos = nx.spring_layout(H, seed=7, k=0.9, weight="weight", iterations=200)
    fig, ax = plt.subplots(figsize=(10, 7.5))
    w = np.array([H[u][v]["weight"] for u, v in H.edges])
    nx.draw_networkx_edges(H, pos, ax=ax, width=0.4 + 1.6 * (w / w.max()) if len(w) else 1, edge_color=AXIS, alpha=0.8)
    if color_by:
        types = [H.nodes[n].get(color_by, "") for n in H.nodes]
        cols = [CATEGORICAL[ENTITY_TYPES_SHOWN.index(t)] if t in ENTITY_TYPES_SHOWN else MUTED for t in types]
    else:
        cols = SERIES_1
    sizes = [30 + 8 * H.nodes[n].get("count", 1) for n in H.nodes]
    nx.draw_networkx_nodes(H, pos, ax=ax, node_size=sizes, node_color=cols, edgecolors=SURFACE, linewidths=1.5)
    top_labels = sorted(H.nodes, key=lambda n: -H.nodes[n].get("weighted_degree", 0))[:label_n]
    for n in top_labels:
        x, y = pos[n]
        ax.text(x + 0.03, y, _short(n, 34), fontsize=7.5, ha="left", va="center", color=INK,
                bbox=dict(boxstyle="round,pad=0.15", fc=SURFACE, ec="none", alpha=0.8))
    if color_by:
        handles = [plt.Line2D([], [], marker="o", ls="", color=CATEGORICAL[i], markersize=7)
                   for i in range(len(ENTITY_TYPES_SHOWN))]
        ax.legend(handles, [ENTITY_TYPE_ES[t] for t in ENTITY_TYPES_SHOWN], loc="lower left")
    ax.set_title(title)
    ax.axis("off")
    _finish(fig, ax, out, f"Componente conexo principal, top {len(H)} nodos por grado ponderado; arista = coaparición en el mismo "
                          "párrafo (entidades) u oración (conceptos). Posiciones 2D ilustrativas; grafo completo en outputs/networks/.")


# --- 9-11 Topics & embeddings --------------------------------------------------------------------

def plot_topic_distribution(summary: pd.DataFrame, out: Path) -> None:
    models = [("tfidf_nmf", "TF-IDF + NMF"), ("lda", "LDA"), ("embedding_kmeans", "Embeddings + k-means")]
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 5.2), sharex=True)
    for ax, (m, name) in zip(axes, models):
        d = summary[summary.model == m].sort_values("share_paragraphs", ascending=False)
        labels = [f"T{t}: " + ", ".join(s.split(", ")[:3]) for t, s in zip(d.topic, d.top_terms)]
        _hbar(ax, labels, (d.share_paragraphs * 100).values, fmt="{:.0f}%")
        ax.set_title(name, fontsize=10)
        ax.set_xlabel("% de párrafos (tema dominante)")
    fig.suptitle("Distribución de temas según tres modelos (sin etiquetas interpretativas)", x=0.01, ha="left",
                 fontweight="bold", fontsize=12)
    fig.tight_layout(rect=(0, 0.03, 1, 0.95))
    _finish(fig, None, out, "Los temas se describen solo con sus 3 términos principales. Acuerdo entre modelos bajo (ver topic_model_agreement.csv).")


def plot_topics_by_section(tbc: pd.DataFrame, summary: pd.DataFrame, out: Path, model: str = "tfidf_nmf") -> None:
    d = tbc[tbc.model == model].pivot(index="chapter", columns="dominant_topic", values="share").fillna(0)
    d = d.reindex([c for c in CHAPTER_ORDER if c in d.index])
    names = summary[summary.model == model].set_index("topic").top_terms.map(lambda s: ", ".join(s.split(", ")[:2]))
    fig, ax = plt.subplots(figsize=(12, 3.8))
    im = ax.imshow(d.values * 100, cmap=BLUE_CMAP, aspect="auto", vmin=0)
    ax.set_yticks(range(len(d.index)), [CHAPTER_SHORT[c] for c in d.index])
    ax.set_xticks(range(d.shape[1]), [f"T{t}\n{names.get(t, '')}" for t in d.columns], fontsize=7)
    for i in range(d.shape[0]):
        for j in range(d.shape[1]):
            v = d.values[i, j] * 100
            if v >= 8:
                ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=7,
                        color="white" if v > 35 else INK)
    cb = fig.colorbar(im, ax=ax, fraction=0.02, pad=0.01)
    cb.set_label("% de párrafos del capítulo", color=INK_2)
    cb.outline.set_visible(False)
    ax.set_title("Temas por capítulo (TF-IDF + NMF, tema dominante por párrafo)")
    for s in ax.spines.values():
        s.set_visible(False)
    _finish(fig, ax, out)


def plot_semantic_embedding_map(emap: pd.DataFrame, method: str, out: Path) -> None:
    """Small multiples: each panel highlights one chapter over the others in grey
    (a scatter can only carry ~3 categorical hues safely)."""
    chapters = [c for c in CHAPTER_ORDER if c in set(emap.chapter)]
    fig, axes = plt.subplots(2, 3, figsize=(12, 7.2), sharex=True, sharey=True)
    for ax, ch in zip(axes.ravel(), chapters):
        other = emap[emap.chapter != ch]
        mine = emap[emap.chapter == ch]
        ax.scatter(other.x, other.y, s=9, color=DEEMPH, linewidths=0)
        ax.scatter(mine.x, mine.y, s=14, color=SERIES_1, edgecolors=SURFACE, linewidths=0.6)
        ax.set_title(f"{CHAPTER_SHORT[ch]} (n={len(mine)})", fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])
        for s in ax.spines.values():
            s.set_color(GRID)
    for ax in axes.ravel()[len(chapters):]:
        ax.axis("off")
    fig.suptitle("Mapa semántico exploratorio de párrafos (UMAP 2D)", x=0.01, ha="left", fontweight="bold", fontsize=12)
    fig.tight_layout(rect=(0, 0.03, 1, 0.95))
    _finish(fig, None, out, f"Embeddings: {method}. La distancia 2D NO mide distancia semántica exacta.")


# --- 12-19 Claims & verification ------------------------------------------------------------------

CLAIM_TYPE_ES = {
    "economico": "Económico", "fiscal": "Fiscal", "empleo": "Empleo", "seguridad": "Seguridad", "salud": "Salud",
    "energia": "Energía", "instituciones": "Instituciones", "corrupcion": "Corrupción",
    "politica_social": "Política social", "infraestructura": "Infraestructura",
    "relaciones_internacionales": "Relaciones internacionales", "otros": "Otros",
}


def plot_claim_categories(claims: pd.DataFrame, out: Path) -> None:
    d = claims[claims.claim_kind == "factual_candidate"].claim_type.value_counts()
    fig, ax = plt.subplots(figsize=(7.5, 4.2))
    _hbar(ax, [CLAIM_TYPE_ES.get(t, t) for t in d.index], d.values)
    ax.set_title("Afirmaciones fácticas candidatas por tipo (sugerido por reglas)")
    ax.set_xlabel("Candidatas")
    _finish(fig, ax, out, "Extracción automática sin revisión humana; tipo asignado por palabras clave + sección.")


def plot_claims_by_section(claims: pd.DataFrame, out: Path) -> None:
    d = claims.groupby(["chapter", "claim_kind"]).size().unstack(fill_value=0)
    d = d.reindex([c for c in CHAPTER_ORDER if c in d.index])
    kinds = [("factual_candidate", "Fáctica candidata"), ("evaluative_candidate", "Evaluativa candidata")]
    fig, ax = plt.subplots(figsize=(8, 3.6))
    y = np.arange(len(d))[::-1]
    left = np.zeros(len(d))
    for i, (k, lab) in enumerate(kinds):
        v = d.get(k, pd.Series(0, index=d.index)).values
        ax.barh(y, v, left=left, height=0.6, color=CATEGORICAL[i], edgecolor=SURFACE, linewidth=2, label=lab)
        left += v
    for yi, tot in zip(y, left):
        ax.text(tot + 5, yi, f"{int(tot)}", va="center", fontsize=7.5, color=INK_2)
    ax.set_yticks(y, [CHAPTER_SHORT[c] for c in d.index])
    ax.xaxis.grid(True); ax.set_axisbelow(True); ax.spines["left"].set_visible(False)
    ax.tick_params(axis="y", length=0)
    ax.legend(loc="lower right")
    ax.set_title("Afirmaciones candidatas por capítulo")
    ax.set_xlabel("Candidatas")
    _finish(fig, ax, out)


def plot_verification_status_distribution(assess: pd.DataFrame, n_unassessed: int, out: Path) -> None:
    counts = assess.assessment.value_counts().reindex(STATUS_ORDER, fill_value=0)
    fig, ax = plt.subplots(figsize=(8.5, 4))
    _hbar(ax, [STATUS_LABELS_ES[s] for s in counts.index], counts.values,
          color=[STATUS_COLORS[s] for s in counts.index])
    ax.set_title(f"Estado de verificación — piloto de {len(assess)} afirmaciones")
    ax.set_xlabel("Afirmaciones evaluadas")
    ax.xaxis.set_major_locator(matplotlib.ticker.MaxNLocator(integer=True))
    _finish(fig, ax, out, f"{n_unassessed} candidatas siguen sin evaluar. El piloto no es una muestra aleatoria: no extrapolar porcentajes al informe.")


def plot_verification_status_by_claim_type(merged: pd.DataFrame, out: Path) -> None:
    d = merged[merged.verification_status != "unassessed"]
    t = d.groupby(["claim_type", "verification_status"]).size().unstack(fill_value=0)
    cols = [s for s in STATUS_ORDER if s in t.columns]
    fig, ax = plt.subplots(figsize=(8.5, 3.8))
    y = np.arange(len(t))[::-1]
    left = np.zeros(len(t))
    for s in cols:
        ax.barh(y, t[s].values, left=left, height=0.6, color=STATUS_COLORS[s], edgecolor=SURFACE, linewidth=2,
                label=STATUS_LABELS_ES[s])
        left += t[s].values
    ax.set_yticks(y, [CLAIM_TYPE_ES.get(x, x) for x in t.index])
    ax.xaxis.set_major_locator(matplotlib.ticker.MaxNLocator(integer=True))
    ax.xaxis.grid(True); ax.set_axisbelow(True); ax.spines["left"].set_visible(False); ax.tick_params(axis="y", length=0)
    ax.legend(loc="lower right", fontsize=7.5)
    ax.set_title("Estado de verificación por tipo de afirmación (piloto)")
    _finish(fig, ax, out, "n pequeño por tipo: descriptivo, no inferencial.")


def normalise_cited_source(s: str) -> str:
    s = str(s)
    rules = [(r"contralor", "Contraloría (CGR)"), (r"procurad", "Procuraduría"), (r"fiscal[ií]a", "Fiscalía"),
             (r"consejo de estado", "Consejo de Estado"), (r"corte", "Cortes"), (r"siif", "SIIF Nación"),
             (r"secop", "SECOP"), (r"superintendencia", "Superintendencias"), (r"dian", "DIAN"), (r"dane", "DANE"),
             (r"campetrol", "CAMPETROL"), (r"cambio", "Revista Cambio"), (r"nota al pie", "Nota al pie"),
             (r"entidad|registros|información|datos|reportes?", "Registros/datos de la entidad (genérico)")]
    for pat, lab in rules:
        if re.search(pat, s, re.I):
            return lab
    return "Otra"


def plot_sources_cited_by_report(claims: pd.DataFrame, out: Path) -> pd.DataFrame:
    c = claims[claims.claim_kind == "factual_candidate"].copy()
    c["cited"] = c.source_cited_in_report.fillna("")
    c["cited_group"] = np.where(c.cited == "", "Sin fuente explícita en la oración", c.cited.map(normalise_cited_source))
    d = c.cited_group.value_counts()
    fig, ax = plt.subplots(figsize=(8, 0.3 * len(d) + 1.2))
    _hbar(ax, d.index.tolist(), d.values,
          color=[DEEMPH if i.startswith("Sin fuente") else SERIES_1 for i in d.index])
    ax.set_title("Fuentes citadas por el informe en afirmaciones fácticas candidatas")
    ax.set_xlabel("Afirmaciones")
    _finish(fig, ax, out, "Detección por patrones ('según…', 'la Contraloría reveló…'); una fuente puede citarse en otra oración del párrafo.")
    return d.rename_axis("cited_source_group").reset_index(name="n_claims")


def plot_sources_used_by_audit(ledger: pd.DataFrame, out: Path) -> None:
    order = ["raw_official_dataset", "official_statistical_publication", "legislation_or_official_document",
             "peer_reviewed_research", "multilateral_organisation", "independent_research", "reputable_journalism",
             "commentary", "social_media", "audited_document", "coverage_of_audited_document"]
    es = {"raw_official_dataset": "Dataset oficial (bruto)", "official_statistical_publication": "Publicación estadística oficial",
          "legislation_or_official_document": "Documento oficial", "peer_reviewed_research": "Investigación arbitrada",
          "multilateral_organisation": "Organismo multilateral", "independent_research": "Investigación independiente",
          "reputable_journalism": "Periodismo", "commentary": "Opinión / columna", "social_media": "Redes sociales",
          "audited_document": "Documento auditado", "coverage_of_audited_document": "Cobertura del informe (no evidencia)"}
    d = ledger.source_type.value_counts().reindex(order, fill_value=0)
    d = d[d > 0]
    fig, ax = plt.subplots(figsize=(8, 0.34 * len(d) + 1.2))
    cols = [DEEMPH if k in ("audited_document", "coverage_of_audited_document") else SERIES_1 for k in d.index]
    _hbar(ax, [es[k] for k in d.index], d.values, color=cols)
    ax.set_title("Fuentes externas usadas por esta auditoría (jerarquía de evidencia)")
    ax.set_xlabel("Fuentes en el registro")
    _finish(fig, ax, out, "Ordenadas por la jerarquía de la metodología §26. Varias piezas periodísticas reproducen un mismo origen (CGR, DIAN, Invías).")


def plot_timeline_of_claims(claims: pd.DataFrame, out: Path) -> pd.DataFrame:
    years = []
    for tp in claims.time_period.dropna():
        for y in re.findall(r"(?:19|20)\d{2}", str(tp)):
            years.append(int(y))
    s = pd.Series(years)
    s = s[(s >= 2010) & (s <= 2036)].value_counts().sort_index()
    fig, ax = plt.subplots(figsize=(9, 3.4))
    ax.bar(s.index, s.values, width=0.7, color=SERIES_1)
    ax.axvspan(2022.6, 2026.6, color="#f0efec", zorder=0)
    ax.text(2024.6, s.max() * 1.04, "Periodo 2022–2026", ha="center", fontsize=8, color=INK_2)
    ax.yaxis.grid(True); ax.set_axisbelow(True)
    ax.set_xticks(range(2010, 2037, 2))
    ax.set_ylim(0, s.max() * 1.15)
    ax.set_title("Años mencionados en las afirmaciones candidatas")
    ax.set_ylabel("Menciones")
    _finish(fig, ax, out, "Un año por mención; una afirmación puede mencionar varios. Sombreado = contexto, no atribución causal.")
    return s.rename_axis("year").reset_index(name="mentions")


def plot_numeric_claims_dashboard(numeric: pd.DataFrame, out: Path) -> None:
    auto = numeric[~numeric.notes.fillna("").str.startswith("RECONSTRUCTED")]
    recon = numeric[numeric.notes.fillna("").str.startswith("RECONSTRUCTED")].copy()
    kind = auto.notes.str.extract(r"\((money|percent|count)\)")[0].map(
        {"money": "Monetaria", "percent": "Porcentaje", "count": "Conteo"}).value_counts()
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(12, 4), gridspec_kw={"width_ratios": [1, 1.6]})
    _hbar(a1, kind.index.tolist(), kind.values)
    a1.set_title("Cifras detectadas por tipo", fontsize=10)
    a1.set_xlabel("Afirmaciones con cifra principal")
    recon["label"] = recon.claim_id + " · " + recon.variable.map(lambda s: _short(s, 42))
    recon = recon.sort_values("difference_percent")
    y = np.arange(len(recon))
    a2.axvline(0, color=AXIS, lw=1)
    a2.scatter(recon.difference_percent, y, s=60, color=SERIES_1, edgecolors=SURFACE, linewidths=2, zorder=3)
    for yi, v in zip(y, recon.difference_percent):
        a2.text(v + 0.05, yi + 0.18, f"{v:+.2f}%", fontsize=7.5, color=INK_2)
    a2.set_yticks(y, recon.label)
    a2.set_xlim(-2, 2)
    a2.xaxis.grid(True); a2.set_axisbelow(True); a2.spines["left"].set_visible(False); a2.tick_params(axis="y", length=0)
    a2.set_title("Reconstrucción: diferencia fuente independiente vs. informe", fontsize=10)
    a2.set_xlabel("Diferencia (%)")
    fig.suptitle("Tablero de afirmaciones numéricas", x=0.01, ha="left", fontweight="bold", fontsize=12)
    fig.tight_layout(rect=(0, 0.03, 1, 0.94))
    _finish(fig, None, out, "0% = el valor coincide. Coincidir en la cifra no valida la interpretación ni la atribución.")


def plot_causal_language(causal: pd.DataFrame, framing_by_chapter: pd.DataFrame, out: Path) -> None:
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(12, 4.2))
    terms = []
    for col in ("marker_core", "marker_extended"):
        for t in causal[col].fillna(""):
            terms += [x.strip() for x in str(t).split(";") if x.strip()]
    d = pd.Series(terms).value_counts().head(14)
    _hbar(a1, d.index.tolist(), d.values)
    a1.set_title("Marcadores causales encontrados", fontsize=10)
    a1.set_xlabel("Ocurrencias")
    f = framing_by_chapter.set_index("chapter").reindex([c for c in CHAPTER_ORDER if c in set(framing_by_chapter.chapter)])
    y = np.arange(len(f))[::-1]
    h = 0.36
    a2.barh(y + h / 2, f.causal_core_per_1k_words, height=h, color=CATEGORICAL[0], label="Núcleo (§14)")
    a2.barh(y - h / 2, f.causal_extended_per_1k_words, height=h, color=CATEGORICAL[1], label="Extendidos")
    a2.set_yticks(y, [CHAPTER_SHORT[c] for c in f.index])
    a2.xaxis.grid(True); a2.set_axisbelow(True); a2.spines["left"].set_visible(False); a2.tick_params(axis="y", length=0)
    a2.legend(loc="lower right")
    a2.set_title("Lenguaje causal por 1.000 palabras", fontsize=10)
    fig.suptitle("Análisis de lenguaje causal (para revisión especial)", x=0.01, ha="left", fontweight="bold", fontsize=12)
    fig.tight_layout(rect=(0, 0.03, 1, 0.94))
    _finish(fig, None, out, "Un marcador causal señala una afirmación a revisar; no prueba ni refuta la causalidad.")


def plot_framing_by_chapter(fbc: pd.DataFrame, out: Path) -> None:
    cols = [c for c in fbc.columns if c.endswith("_per_1k_words") and not c.startswith(("positive", "negative", "causal"))]
    f = fbc.set_index("chapter").reindex([c for c in CHAPTER_ORDER if c in set(fbc.chapter)])[cols]
    labels = [c.replace("_per_1k_words", "").replace("frame_", "marco: ") for c in cols]
    fig, ax = plt.subplots(figsize=(12, 3.8))
    im = ax.imshow(f.values, cmap=BLUE_CMAP, aspect="auto", vmin=0)
    ax.set_yticks(range(len(f)), [CHAPTER_SHORT[c] for c in f.index])
    ax.set_xticks(range(len(cols)), labels, rotation=35, ha="right", fontsize=7.5)
    for i in range(f.shape[0]):
        for j in range(f.shape[1]):
            v = f.values[i, j]
            ax.text(j, i, f"{v:.1f}", ha="center", va="center", fontsize=6.5, color="white" if v > f.values.max() * 0.6 else INK)
    cb = fig.colorbar(im, ax=ax, fraction=0.02, pad=0.01)
    cb.set_label("por 1.000 palabras", color=INK_2); cb.outline.set_visible(False)
    for s in ax.spines.values():
        s.set_visible(False)
    ax.set_title("Lenguaje evaluativo y marcos narrativos por capítulo (léxicos exploratorios)")
    _finish(fig, ax, out, "Conteos de léxico transparente (src/lexicons.py). Describen uso de palabras, no intención ni sesgo.")


# --- 22-26 Stylometry / sentiment -------------------------------------------------------------------

def plot_stylometry_heatmap(features: pd.DataFrame, segments: pd.DataFrame, out: Path, cols: list[str]) -> None:
    X = features.set_index("segment_id")[cols]
    Z = (X - X.mean()) / X.std()
    fig, ax = plt.subplots(figsize=(13, 5))
    div = LinearSegmentedColormap.from_list("div", ["#184f95", "#6da7ec", "#f0efec", "#e66767", "#b3302f"])
    im = ax.imshow(Z.T.values, cmap=div, aspect="auto", vmin=-3, vmax=3)
    ax.set_yticks(range(len(cols)), cols, fontsize=7.5)
    seg = segments.set_index("segment_id")
    ticks = list(range(0, len(Z), 3))
    ax.set_xticks(ticks, [f"{Z.index[i]}\np{seg.loc[Z.index[i], 'page_start']}" for i in ticks], fontsize=6.5)
    ch = seg.loc[Z.index, "chapter"].values
    for i in range(1, len(ch)):
        if ch[i] != ch[i - 1]:
            ax.axvline(i - 0.5, color=INK, lw=0.8)
    cb = fig.colorbar(im, ax=ax, fraction=0.015, pad=0.01)
    cb.set_label("z-score", color=INK_2); cb.outline.set_visible(False)
    ax.set_title("Mapa estilométrico por segmento (~700 palabras); líneas = límites de capítulo")
    _finish(fig, ax, out, "Rasgos estandarizados. Un contraste de color indica diferencia estilística, no autoría ni uso de IA.")


def plot_similarity_matrix(sim: pd.DataFrame, segments: pd.DataFrame, out: Path, title: str, cmap=None) -> None:
    fig, ax = plt.subplots(figsize=(7.5, 6.5))
    im = ax.imshow(sim.values, cmap=cmap or BLUE_CMAP, aspect="equal")
    seg = segments.set_index("segment_id")
    ch = seg.loc[sim.index, "chapter"].values
    for i in range(1, len(ch)):
        if ch[i] != ch[i - 1]:
            ax.axvline(i - 0.5, color=INK, lw=0.6); ax.axhline(i - 0.5, color=INK, lw=0.6)
    ticks = list(range(0, len(sim), 5))
    ax.set_xticks(ticks, [sim.index[i] for i in ticks], fontsize=6.5, rotation=90)
    ax.set_yticks(ticks, [sim.index[i] for i in ticks], fontsize=6.5)
    cb = fig.colorbar(im, ax=ax, fraction=0.04, pad=0.02); cb.outline.set_visible(False)
    ax.set_title(title, fontsize=11)
    _finish(fig, ax, out, "Segmentos en orden del documento; líneas = límites de capítulo.")


def plot_change_points(scores: pd.DataFrame, cps: pd.DataFrame, out: Path) -> None:
    fig, ax = plt.subplots(figsize=(12, 3.6))
    x = np.arange(len(scores))
    ax.plot(x, scores.pc1, color=SERIES_1, lw=2, marker="o", ms=4, mec=SURFACE, mew=1.5, label="PC1 estilométrico")
    ch = scores.chapter.values
    for i in range(1, len(ch)):
        if ch[i] != ch[i - 1]:
            ax.axvline(i - 0.5, color=AXIS, lw=1)
    idx = {s: i for i, s in enumerate(scores.segment_id)}
    for _, r in cps.iterrows():
        i = idx[r.break_before_segment]
        ax.axvline(i - 0.5, color=CATEGORICAL[1], lw=2 if r.robust else 1.2, alpha=0.9 if r.robust else 0.6)
        ax.text(i - 0.4, scores.pc1.max() * 1.18, f"{r.n_configs_detected}/{r.n_configs}", fontsize=7, color=INK_2, va="top")
    ax.set_xticks(x[::4], [f"{s}\np{p}" for s, p in zip(scores.segment_id[::4], scores.pages.astype(str).str.split('-').str[0][::4])], fontsize=6.5)
    ax.yaxis.grid(True); ax.set_axisbelow(True)
    handles = [plt.Line2D([], [], color=SERIES_1, lw=2), plt.Line2D([], [], color=CATEGORICAL[1], lw=1.5),
               plt.Line2D([], [], color=AXIS, lw=1)]
    ax.set_ylim(scores.pc1.min() * 1.1, scores.pc1.max() * 1.25)
    ax.legend(handles, ["PC1 estilométrico", "Punto de cambio (n configuraciones que lo detectan)", "Límite de capítulo"],
              loc="lower left", bbox_to_anchor=(0, 1.0), ncol=3)
    ax.set_title("Línea de tiempo de cambios estilísticos (detección de puntos de cambio, 12 configuraciones)", pad=28)
    _finish(fig, ax, out, "Ningún punto de cambio es robusto (≥ 2/3 de configuraciones). Los más frecuentes coinciden con límites de capítulo.")


def plot_stylometry_pca(scores: pd.DataFrame, pca_var: pd.DataFrame, out: Path) -> None:
    chapters = [c for c in CHAPTER_ORDER if c in set(scores.chapter)]
    fig, axes = plt.subplots(2, 3, figsize=(11, 6.8), sharex=True, sharey=True)
    for ax, ch in zip(axes.ravel(), chapters):
        o, m = scores[scores.chapter != ch], scores[scores.chapter == ch]
        ax.scatter(o.pc1, o.pc2, s=16, color=DEEMPH, linewidths=0)
        ax.scatter(m.pc1, m.pc2, s=30, color=SERIES_1, edgecolors=SURFACE, linewidths=1.2)
        for _, r in m[m.flag_stylistic_outlier].iterrows():
            ax.annotate(f"{r.segment_id} (atípico)", (r.pc1, r.pc2), fontsize=7, color=INK, xytext=(4, 4), textcoords="offset points")
        ax.set_title(f"{CHAPTER_SHORT[ch]} (n={len(m)})", fontsize=10)
        ax.xaxis.grid(True); ax.yaxis.grid(True); ax.set_axisbelow(True)
    for ax in axes.ravel()[len(chapters):]:
        ax.axis("off")
    v = pca_var.explained_variance_ratio.values
    fig.supxlabel(f"PC1 ({v[0]*100:.0f}% var.)", fontsize=9, color=INK_2)
    fig.supylabel(f"PC2 ({v[1]*100:.0f}% var.)", fontsize=9, color=INK_2)
    fig.suptitle("Mapa estilométrico PCA de segmentos", x=0.01, ha="left", fontweight="bold", fontsize=12)
    fig.tight_layout(rect=(0.02, 0.04, 1, 0.95))
    _finish(fig, None, out, "Atípico = distancia de Mahalanobis > χ²(0,975). Diferencia estilística ≠ autoría ni uso de IA.")


def plot_sentiment(sent: pd.DataFrame, out: Path) -> None:
    f = sent.set_index("chapter").reindex([c for c in CHAPTER_ORDER if c in set(sent.chapter)])
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(12, 3.6))
    _hbar(a1, [CHAPTER_SHORT[c] for c in f.index], (f.lexicon_neg_share * 100).values, fmt="{:.0f}%")
    a1.set_title("Léxico evaluativo: % de términos negativos", fontsize=10)
    a1.set_xlabel("% negativos / (positivos + negativos)")
    _hbar(a2, [CHAPTER_SHORT[c] for c in f.index], f.mean_model_score.values, fmt="{:.2f}", color=CATEGORICAL[1])
    a2.set_title("Modelo 'sentiment-analysis-spanish' (0–1)", fontsize=10)
    a2.set_xlabel("Puntaje medio (entrenado con reseñas; fuera de dominio)")
    rho = f.model_lexicon_spearman.iloc[0]
    fig.suptitle(f"Sentimiento exploratorio: dos métodos que no coinciden (Spearman ρ = {rho:.2f})", x=0.01, ha="left",
                 fontweight="bold", fontsize=12)
    fig.tight_layout(rect=(0, 0.04, 1, 0.92))
    _finish(fig, None, out, "Ninguno de los dos métodos mide sesgo ni veracidad; su desacuerdo es un resultado negativo documentado.")
